---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: longhorn-role
rules:
  - apiGroups:
      - '*'
    resources:
      - services
      - pods
      - deployments
    verbs:
      - '*'
...
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: longhorn-service
  namespace: default
subjects:
  - kind: User
    name: 'system:serviceaccount:default:default'
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: longhorn-role
  apiGroup: rbac.authorization.k8s.io
...
