---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: longhorn-ui
  labels:
    app: longhorn-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-ui
  template:
    metadata:
      labels:
        app: longhorn-ui
    spec:
      containers:
        - name: longhorn-ui
          image: 'rancher/longhorn-ui:b09b215'
          env:
            - name: LONGHORN_MANAGER_IP
              value: 'http://longhorn-manager:9500'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
      restartPolicy: Always
...
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-ui
spec:
  ports:
    - name: '8000'
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: longhorn-ui
  type: NodePort
...
