apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: longhorn-driver
  labels:
    app: longhorn-driver
spec:
  selector:
    matchLabels:
      app: longhorn-driver
  template:
    metadata:
      labels:
        app: longhorn-driver
    spec:
      containers:
      - name: longhorn-driver
        image: rancher/storage-longhorn:11a4f5a
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run
          name: longhorn-storage-claim0
        - mountPath: /var/run
          name: longhorn-storage-claim1
        - mountPath: /host/dev
          name: longhorn-storage-claim2
        - mountPath: /var/lib/rancher/volumes
          name: longhorn-storage-claim3
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /run
        name: longhorn-storage-claim0
      - hostPath:
          path: /var/run
        name: longhorn-storage-claim1
      - hostPath:
          path: /dev
        name: longhorn-storage-claim2
      - hostPath:
          path: /var/lib/rancher/volumes
        name: longhorn-storage-claim3
