apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: longhorn-manager
  labels:
    app: longhorn-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app: longhorn-manager
    spec:
      initContainers:
        - name: longhorn-engine-binary
          image: 'rancher/longhorn-engine:046b5a5'
          command: ['sh', '-c', 'cp -r /usr/local/bin/* /longhorn']
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /longhorn
            name: longhorn-manager-claim3
      containers:
        - name: longhorn-manager
          image: 'rancher/longhorn-manager:63f2927-dirty'
          args:
            - launch-manager
            - '-d'
            - '--orchestrator'
            - k8s
            - '--engine-image'
            - 'rancher/longhorn-engine:046b5a5'
            - '--etcd-servers'
            - 'http://longhorn-etcd:2379'
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/dev
              name: longhorn-manager-claim0
            - mountPath: /var/run
              name: longhorn-manager-claim1
            - mountPath: /var/lib/rancher/longhorn
              name: longhorn-manager-claim2
            - mountPath: /usr/local/bin
              name: longhorn-manager-claim3
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      volumes:
        - name: longhorn-manager-claim0
          hostPath:
            path: /dev
        - name: longhorn-manager-claim1
          hostPath:
            path: /var/run
        - name: longhorn-manager-claim2
          hostPath:
            path: /var/lib/rancher/longhorn
        - name: longhorn-manager-claim3
          emptyDir: {}
