---
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: longhorn-ui
  labels:
    app: longhorn-ui
spec:
  selector:
    matchLabels:
      app: longhorn-ui
  template:
    metadata:
      labels:
        app: longhorn-ui
    spec:
      containers:
        - name: longhorn-ui
          image: 'rancher/longhorn-ui:b09b215'
          env:
            - name: LONGHORN_MANAGER_IP
              value: 'http://longhorn-manager:9500'
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "LONGHORN_MANAGER_IP=http://$LONGHORN_MANAGER_SERVICE_HOST:$LONGHORN_MANAGER_SERVICE_PORT_9500 && envsubst '${LONGHORN_MANAGER_IP}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
          ports:
            - containerPort: 8000
      restartPolicy: Always
...
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-ui
  name: longhorn-ui
spec:
  ports:
    - name: '8000'
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: longhorn-ui
  type: NodePort
...
